config/routes.rb
Rails.application.routes.draw do
  get 'relationships/followings'
  get 'relationships/followers'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: "homes#top"
  get "home/about" => "homes#about"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get 'search', to: "users#search"
  end

  get "search" => "searches#search"
  get "searches/index"
  get "search_book" => "books#search_book"

  resources :chats, only: [:show, :create]

  resources :groups do
    get "join" => "groups#join"
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
before_action :authenticate_user!

  def index
    @range = params[:range]
    @users = User.looks(params[:search], params[:word])
    @books = Book.looks(params[:search], params[:word])
  end

  def search
    @range = params[:range]
    if @range == "User"
      @users = User.looks(params[:search], params[:word])
      render :index
    else
      @books = Book.looks(params[:search], params[:word])
      render :index
    end
  end
  
  

end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_search.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='mx-auto form-inline'>
      <% if user_signed_in? %>
        <div class="search_form mt-3">
          <%= form_with url: search_path, local: true, method: :get do |f| %>
            <%= f.text_field :word %>
            <%= f.select :range, options_for_select([['User'], ['Book']]) %>
            <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backward_match"], ["部分一致","partial_match"]]) %>
            <%= f.submit "検索", class: "btn btn-primary" %>
          <% end %>
        </div>
        <div class="search_book ml-3 mt-3">
          <%= form_with url: search_book_path, local: true, method: :get do |f| %>
            <%= f.text_field :keyword %>
            <%= f.submit "タグ検索", class: "btn btn-primary" %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/searches/index.html.erb
<table class="table table-hover table-inverse">
  <!--検索対象モデルがUserの時 -->
  <% if @range == "User" %>
    <h2>Users search for "<%= params[:word] %>"</h2>
    <thead>
      <tr>
        <th>Profile Image</th>
        <th>User Name</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= image_tag user.get_profile_image, size:'50x50' %></td>
          <td><%= user.name %></td>
          <td><%= link_to "Show", user_path(user) %></td>
        </tr>
      <% end %>
    </tbody>
  <% else %>
    <!--検索対象モデルがUserではない時(= 検索対象モデルがBookの時) -->
    <thead>
      <h2>Books search for "<%= params[:word] %>"</h2>
      <tr>
        <th>Profile Image</th>
        <th>Title</th>
        <th>Opinion</th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
        <tr>
          <td><%= image_tag book.user.get_profile_image, size:'50x50' %></td>
          <td>
            <%= link_to book_path(book) do %>
              <%= book.title %>
            <% end %>
          </td>
          <td><%= book.body %></td>
          <td><%= link_to book.category, search_book_path(keyword: book.category) %></td>
          <td class="favorite_<%= book.id %>">
            <%= render "favorites/favorite", book: book %>
          </td>
          <td>コメント数：<%= book.post_comments.count %></td>
          <td><%= render 'layouts/star-read', book: book %></td>
        </tr>
      <% end %>
    </tbody>
  <% end %>
</table>